### ISSUE TITLE
Consider to create a license

### ISSUE THREAD

**Issue by bofeiw** [reuschj/RotatableStack#1]
Hi, amazing work! I wanna use this package in my project, but there's no license in this repo. Would you consider to add a license? Thanks!

**Comment by reuschj** [comment]
Will do. In the meantime, you are free to use it in your project. Also, if you find any bugs or have any improvements, feel free to contribute! Thanks!

**Comment by reuschj** [comment]
Just merged a PR adding a GPL license. Hope that works for you!
