### ISSUE TITLE
support for .alignment and .spacing parameters

### ISSUE THREAD

**Issue by kcochibili** [reuschj/RotatableStack#4]
Amazing project you have here!
 I am wondering if it is possible to add support for alignment and spacing
```
 VStack(alignment: .center, spacing: 0) {

}
```

just like in a regular `VStack`, or `HStack`
is that possible?

**Comment by reuschj** [comment]
This is a great idea! I took a pass at adding this today and I'll add you to a PR to review.

**Comment by reuschj** [comment]
I can't seem to tag you, but here's the PR: https://github.com/reuschj/RotatableStack/pull/5

Feel free to take a look and comment. I added both horizontal and vertical alignment params, since it uses one for landscape and another for portrait. However, I made an alternative initializer that just takes alignment and translates it as needed. So, one initializer for convenience, another for flexibility.

**Comment by reuschj** [comment]
I also gave it a quick try on an iOS project using it and seems to be working. If you want test, just set it to pull the branch `feat/add_alignment_and_spacing_params` instead of version tag.

**Comment by kcochibili** [comment]
Wow, that was fast!
Thanks for the quick response and the creative solutions you implemented; like the ``FlexAlighnment`` idea. 

I am not sure why GitHub didn't let you tag me, but anyways I have seen the new code and it looks ready to merge. Thanks again. 

Side note: your approach in this library, helped me create another library that deals with GeometryReader [here](https://github.com/kcochibili/GeometryReaderStackView)

**Comment by reuschj** [comment]
Awesome! I'll take a look at your project! Took a quick glance and looks cool... will dig into it more when I have a chance!

**Comment by reuschj** [comment]
v1.1.0 released https://github.com/reuschj/RotatableStack/releases/tag/1.1.0

Thanks for the suggestion!

**Comment by reuschj** [comment]
Btw... the GeometryReader project looks great. My only suggestion is to make it into a Swift Package. Nice work!

**Comment by reuschj** [comment]
I realized I forgot to update the README... here's the PR, if you want to take a scan:

https://github.com/reuschj/RotatableStack/pull/6

**Comment by kcochibili** [comment]
Thanks for the feedback on my project, I will make it into a swift package.

**Comment by kcochibili** [comment]
I will now go ahead and now close this issue, thanks again for the proactive updates.
